version: "3.8"
services:
  studio:
    image: supabase/studio:latest
    restart: unless-stopped
    ports:
      - "54323:3000"  # Changed from 3000 to 54323
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}

  db:
    image: supabase/postgres:15.1.0.117
    restart: unless-stopped
    ports:
      - "54322:5432"  # Changed from 5432 to 54322
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - db-data:/var/lib/postgresql/data

  kong:
    image: kong:2.8.1
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
    volumes:
      - ./kong.yml:/var/lib/kong/kong.yml:ro

  auth:
    image: supabase/gotrue:v2.91.0
    depends_on:
      - db
    restart: unless-stopped
    environment:
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_JWT_EXP: 3600
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_HOST: db
      GOTRUE_DB_PORT: 5432
      GOTRUE_DB_NAME: postgres
      GOTRUE_DB_USER: postgres
      GOTRUE_DB_PASSWORD: ${DB_PASSWORD}
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_API_HOST: 0.0.0.0

  rest:
    image: postgrest/postgrest:v11.1.0
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://postgres:${DB_PASSWORD}@db:5432/postgres
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon

  realtime:
    image: supabase/realtime:v2.9.3
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}

  storage:
    image: supabase/storage-api:v0.40.4
    depends_on:
      - db
      - rest
    restart: unless-stopped
    environment:
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@db:5432/postgres
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    volumes:
      - uploads:/var/lib/storage

volumes:
  db-data:
  uploads:
